services:
  database:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server
    env_file:
      - .env
    ports:
      - 1433:1433
    volumes:
      - database_volume:/sql_server/

  app:
    build: .
    container_name: boardcampApi
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - database

volumes:
  database_volume:
